### ISSUE TITLE
Get this set up to publish to plugins/drone-devpi on Docker Hub

### ISSUE THREAD

**Issue by gtaylor** [drone-plugins/drone-devpi#2]
I've currently got it publishing Docker images to my personal gtaylor/drone-devpi repo on Docker Hub so that we can use it immediately at work.

@bradrydzewski Feel free to re-point this where it should be on Docker Hub at your leisure.

**Comment by bradrydzewski** [comment]
done!

**Comment by gtaylor** [comment]
Awesome, thanks! Time to close the loop in Python land today at work.
